# Generated by Django 2.2.10 on 2020-06-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name product')),
                ('desc', models.TextField(verbose_name='description product')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='price')),
                ('image', models.ImageField(blank=True, default='no-image.jpg', upload_to='products_images')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity product')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='add date product')),
            ],
        ),
    ]
